### ISSUE TITLE
Окончание работы потока с расписанием после неудачной попытки обращения к Google-таблице.

### ISSUE THREAD

**Issue by Xapulc** [Xapulc/TimetableVKBot#2]
Упал ночью с ошибкой.
```
[VKBottle] While parent_processor was handling error occurred 

Traceback (most recent call last):
  File "/home/xapulc/.local/lib/python3.6/site-packages/vkbottle/framework/framework/swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "/home/xapulc/.local/lib/python3.6/site-packages/vkbottle/framework/bot/processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "/home/xapulc/.local/lib/python3.6/site-packages/vkbottle/framework/bot/processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "run.py", line 26, in wrapper
    await bot.get_answer(ans, message_text, chat_flg=False)
  File "/home/xapulc/programs/python/TimetableVKBot/Bot.py", line 53, in get_answer
    answer = timetable.make_notification(time="now")
  File "/home/xapulc/programs/python/TimetableVKBot/Timetable.py", line 50, in make_notification
    data = self._get_record_on_time(pd.read_csv(self._link), time)
  File "/home/xapulc/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/xapulc/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 435, in _read
    filepath_or_buffer, encoding, compression
  File "/home/xapulc/.local/lib/python3.6/site-packages/pandas/io/common.py", line 183, in get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "/home/xapulc/.local/lib/python3.6/site-packages/pandas/io/common.py", line 137, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```
После неё завершилась работа потока, поэтому в 8 утра не пришло уведомление вопреки расписанию.

**Comment by Xapulc** [comment]
Пофишено в [последнем коммите](https://github.com/Xapulc/TimetableVKBot/commit/1a53ea808ccfc52975d7806c489fcb2a9e648172). Теперь при ошибке `HTTPError` будет отправляться `None` в бота, а он будет принимать решения, исходя из этого значения.
